# Web Scrapping Review from Trip advisor

In [22]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
from time import sleep
from random import randint
import matplotlib.pylab as plt

## Web Scraping

In [13]:
# Since the page number changes by 5 in the next url page
page = np.arange(5, 5001, 5)  
Name = []
Title = []
Review = []
Rating = []
for pages in page:
    # for loop to collect the Mutiple Pages as defined
    url = 'https://www.tripadvisor.in/Hotel_Review-g304554-d307116-Reviews-or' + str(
        pages
    ) + '-Grand_Hyatt_Mumbai_Hotel_Residences-Mumbai_Maharashtra.html#REVIEWS'

    # import the Url details to Python
    req = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
    html = req.content

    # Put it in soup
    sleep(randint(2, 8))  
    soup = BeautifulSoup(html, 'html.parser')

    # for loop to extract Customer Names
    for a in soup.find_all('a', class_='ui_header_link _1r_My98y'):
        Name.append(a.get_text(strip=True))
        
    # for loop to extract Review Title
    for a in soup.find_all('div', class_='glasR4aX'):
        Title.append(a.get_text(strip=True))

    # for loop to extract Reviews
    for a in soup.find_all('q', class_='IRsGHoPm'):
        Review.append(a.get_text())

    # for loop to extract Review Rating
    for a in soup.find_all('div', class_='nf9vGX55'):
        # a.span['class'] is used to only select the span class text which has the rating ['ui_bubble_rating', 'bubble_50']
        Rating.append(a.span['class'])

In [16]:
# Extraction of the Rating out of --> this format text ['ui_bubble_rating', 'bubble_50'] generated through above for loop
Final_Rating = []
for i in Rating:
    # select only 'bubble_50' for the list and converted to string to extarct the rating
    bubble_rating = str(i[1])
    # selected the 2nd last letter which is the rating and converted to integer
    Final_Rating.append(int(bubble_rating[-2]))

In [17]:
# Data Frame created for teh details extracted 
df=pd.DataFrame({'Customer_name':Name,'Rating':Final_Rating,'Review_Title':Title,'Review':Review})
df

,Customer_name,Rating,Review_Title,Review
0,maneshpreet26,5,Unforgettable experience..amazing staycation e...,We visited Grand Hyatt on the occasion of my s...
1,Majnu gosavi,5,All about in love with grand Hyatt hotel,तुम्हारी क्या तारीफ करू तुम्ह ही तो तारीफ हो ...
2,Akash Bhosale,5,Most Knowledgeable Trainer,I was fascinated by the Diet and Exercise know...
3,Mahek Dugar,5,A night stay at Grand Hyatt Mumbai,"absolutely loved the stay. amazing food, ambie..."
4,Jaslin,4,Staycation,I had booked Grand Hyatt Santacruz for Staycat...
...,...,...,...,...
4995,anticorpo,4,Very Competent,Excellent international hotel with all things ...
4996,David B,5,Luxurious,This hotel is situated near Mumbai airport but...
4997,rahekt,4,the co-operation was the best,the co-operation was the best and services was...
4998,TravlAdvisor,4,Best Italian Restaurant,Hotel is located very close to the Domestic Ai...
4999,Getabreak,5,"Quiet, comfortable and good food",I have stayed here a few times over the past 1...

In [18]:
# Saved the data frame in csv file
df.to_csv('Tripadvisor_Grand_Hyatt_Review.csv')

## Data Frame

In [21]:
df_new=pd.read_csv('Tripadvisor_Grand_Hyatt_Review.csv')
df_new

,Unnamed: 0,Customer_name,Rating,Review_Title,Review
0,0,maneshpreet26,5,Unforgettable experience..amazing staycation e...,We visited Grand Hyatt on the occasion of my s...
1,1,Majnu gosavi,5,All about in love with grand Hyatt hotel,तुम्हारी क्या तारीफ करू तुम्ह ही तो तारीफ हो ...
2,2,Akash Bhosale,5,Most Knowledgeable Trainer,I was fascinated by the Diet and Exercise know...
3,3,Mahek Dugar,5,A night stay at Grand Hyatt Mumbai,"absolutely loved the stay. amazing food, ambie..."
4,4,Jaslin,4,Staycation,I had booked Grand Hyatt Santacruz for Staycat...
...,...,...,...,...,...
4995,4995,anticorpo,4,Very Competent,Excellent international hotel with all things ...
4996,4996,David B,5,Luxurious,This hotel is situated near Mumbai airport but...
4997,4997,rahekt,4,the co-operation was the best,the co-operation was the best and services was...
4998,4998,TravlAdvisor,4,Best Italian Restaurant,Hotel is located very close to the Domestic Ai...
4999,4999,Getabreak,5,"Quiet, comfortable and good food",I have stayed here a few times over the past 1...